import type { BriefingRecord } from "./db/schema";

export const MOCK_BRIEFING: BriefingRecord = {
  id: "mock-001",
  date: new Date().toISOString().split("T")[0],
  personaKey: "default",
  articlesFetched: 142,
  generatedAt: new Date().toISOString(),
  sections: {
    summary: [
      "Agentic AI is entering enterprise procurement as a standard line item — not a pilot.",
      "EU AI Act enforcement has begun; first fines signal regulators mean business.",
      "Claude 4 Opus context window changes make RAG architecture decisions less critical.",
    ],
    quickHits: "**OpenAI releases o3-mini pricing at 60% lower than o3** — competitive pressure intensifies. **Mistral releases Codestral 2501** — open-source coding model closes gap with GPT-4o on HumanEval. **LangGraph v0.3 ships persistent memory** — stateful agents now 40% easier to build.",
    contentIdeas: "**Post angle 1:** The EU just fined three companies €2.1M for deploying AI without conformity assessment. The grace period is over — here's the 3-item checklist every enterprise team needs. **Post angle 2:** 500K enterprise Copilot Workspace seats in 90 days. Agentic coding is now a procurement line item. What this means for your team's review process.",
    driveTime: "**Drive Time — Signal 1: EU AI Act Enforcement**\n\nGood morning. Let's talk about what happened yesterday in Brussels.\n\nThe EU's AI Office fined three companies a combined €2.1 million for deploying high-risk AI systems without conformity assessments. These are not giants — they're mid-market HR tech companies.\n\nHere's what this means for you: the grace period is over. If your system touches hiring, credit, healthcare, or critical infrastructure, you need a conformity assessment now. Not in Q3. Now.\n\nThe practical checklist: First, classify your system under Annex III. Second, initiate a conformity assessment. Third, document your training data provenance.\n\nNIST AI RMF alignment gets you 60–70% of the way there. If you've done the RMF work, you're not starting from zero.\n\nBottom line: the companies fined next will be the ones who thought they had more time.",
    salesIntel: "**Buyer signal:** EU AI Act enforcement creates urgency for compliance tooling buyers. Decision-makers who were 'monitoring' are now in active evaluation mode. Conversation opener: 'I saw the EU AI Office issued its first fines this week — how is your team thinking about conformity assessments for your AI systems?' **Pain point surfaced:** Most enterprises don't have training data provenance documentation — that's what the first three audits focused on.",
    explainers: "**What is the EU AI Act?** The EU AI Act is the world's first comprehensive AI law. Think of it like GDPR, but for AI systems instead of personal data. It classifies AI systems by risk level (like how buildings are classified by occupancy type) and requires different compliance steps for each level. High-risk systems — think AI used in hiring, credit scoring, or healthcare — need a 'conformity assessment' before they can be deployed in EU markets. **Key terms:** Conformity assessment (the compliance audit), Annex III (the list of high-risk AI use cases), Notified Body (an accredited third-party auditor).",
    strategyBrief: "**Strategic risk:** Organizations deploying AI in HR, credit, healthcare, or critical infrastructure without conformity assessments now face material legal exposure. The €2.1M in fines is precedent-setting, not ceiling-setting. **90-day action:** Commission a gap analysis against EU AI Act Annex III for all deployed AI systems. Prioritize HR and credit scoring tools. NIST AI RMF alignment covers ~65% of requirements — start there. **Opportunity:** Early compliance becomes a procurement advantage with EU customers demanding vendor conformity statements.",
  },
  signals: [
    {
      number: 1,
      title: "EU AI Act Article 6 enforcement begins — first €2.1M in fines issued",
      classification: "Governance Alert",
      whatHappened: "The EU AI Office issued its first enforcement actions under the EU AI Act, fining three mid-market companies for deploying high-risk AI systems — automated CV screening and credit scoring tools — without completing required conformity assessments.",
      whyItMatters: "This signals the end of the regulatory grace period. The EU is moving faster than most enterprises planned for, and the fines establish precedent for what triggers enforcement.",
      industryImpact: "Any AI system touching HR, credit, healthcare, or critical infrastructure must now have a conformity assessment completed before deployment in EU markets. This adds 2–4 months to release timelines for in-scope systems.",
      roleImpact: "Compliance officers and legal teams are now in active evaluation mode. Product and engineering teams need to add conformity assessment milestones to roadmaps for any EU-facing AI feature.",
      myTake: "The companies fined are mid-market, not giants. Regulators are making examples. The message: they will go after whoever is easiest to audit, not whoever is biggest.",
      hook: "The EU just fined three companies €2.1M for deploying AI without a conformity assessment. The grace period is over.",
      contentAngle: "Post this as a wake-up call with the 3-item compliance checklist. Frame it as 'the thing your legal team is about to bring up in your next all-hands.'",
      salesIntel: "Decision-makers who were 'monitoring' EU AI Act are now in active evaluation. Lead with: 'I saw the first EU AI Act fines dropped this week — how are you thinking about your conformity assessment timeline?'",
      explainer: "A conformity assessment is like a building inspection before you can open to the public — except for AI systems. An accredited third party reviews your system's documentation, training data, and risk controls before you're allowed to deploy in EU markets.",
      executiveBrief: "Material legal exposure now exists for any EU-deployed AI system in Annex III categories. Recommend immediate gap analysis. NIST AI RMF alignment covers ~65% of requirements — teams already on RMF are best positioned.",
    },
    {
      number: 2,
      title: "GitHub Copilot Workspace hits 500K enterprise seats in 90 days",
      classification: "Strategic Signal",
      whatHappened: "GitHub reported that Copilot Workspace — its agentic coding environment that takes a GitHub Issue and proposes, implements, and tests a fix end-to-end — reached 500,000 enterprise seats in its first 90 days of GA.",
      whyItMatters: "Agentic coding is now a standard enterprise procurement line item, not an experiment. This scale validates the market faster than any analyst prediction.",
      industryImpact: "Technology, SaaS, and any industry with internal engineering teams faces a new baseline expectation: competitors are shipping AI-assisted development. Teams without a Copilot strategy are already behind.",
      roleImpact: "Engineering leaders need a toolchain decision now. Product managers need to understand that AI-assisted development changes velocity assumptions and review workflows.",
      myTake: "500K seats in 90 days is a product-market fit signal at the same scale as Slack's early growth. The SDLC is being restructured around human-in-the-loop review of agent output, not human-in-the-loop writing of code.",
      hook: "500K enterprise seats in 90 days. Agentic coding is not a pilot anymore — it's a procurement line item.",
      contentAngle: "Write about what changes when the engineer reviews AI output instead of writing code. The junior engineer career path post, the code review checklist post, or the 'what I learned after 90 days of Copilot Workspace' format.",
      salesIntel: "For sales teams selling into tech/engineering buyers: this is the conversation opener. 'Your competitors are evaluating Copilot Workspace — how is your team thinking about AI-assisted development?' Pain point: teams without a strategy feel behind.",
      explainer: "Agentic coding means the AI doesn't just suggest the next line — it reads the whole issue, proposes a solution, writes the code, and runs the tests. The engineer's job shifts from writing to reviewing. Like having a junior dev who can code anything but needs a senior to check the work.",
      executiveBrief: "Engineering productivity baseline is shifting. Organizations that standardize on AI-assisted development tools in the next 6 months will have a structural velocity advantage. Recommend a toolchain evaluation this quarter with a decision before H2 budget planning.",
    },
    {
      number: 3,
      title: "NIST AI RMF 1.1 draft adds Agentic AI section with human override requirements",
      classification: "Governance Alert",
      whatHappened: "NIST published the AI RMF 1.1 draft, adding a dedicated section on Agentic AI systems covering autonomous decision loops, human override mechanisms, audit trail specifications, and multi-agent coordination risks.",
      whyItMatters: "NIST RMF is the de facto governance standard for US federal contractors and increasingly for regulated industries. Agentic systems now require explicit governance design, not just general AI risk management.",
      industryImpact: "Healthcare, financial services, and government contractors using or evaluating agentic AI tools (coding agents, autonomous workflows, AI-driven analytics) now have formal guidance requirements to design against.",
      roleImpact: "Compliance officers and risk teams have a concrete framework to audit against. Engineering teams building agentic systems need to retrofit or build human override mechanisms before this becomes an audit requirement.",
      myTake: "NIST is six months ahead of where most enterprise architecture teams think the governance conversation is. If you're building agents today without override mechanisms, you're building technical debt that will be expensive to retrofit.",
      hook: "NIST says human-in-the-loop is not enough for agentic AI. Here's what human-on-the-loop actually means in practice.",
      contentAngle: "Explain the difference between 'human-in-the-loop' and 'human-on-the-loop' — it's a genuinely useful distinction that most audiences haven't heard. Great educational post format.",
      salesIntel: "For any company selling governance, compliance, or AI risk tools: this is your buying trigger. 'NIST just added agentic AI requirements to RMF 1.1 — does your current risk framework cover autonomous decision loops?' Targets: compliance officers, CISOs, GCs.",
      explainer: "Human-in-the-loop means a human approves every decision the AI makes. Human-on-the-loop means a human monitors and can override — but the AI runs autonomously until they do. Think autopilot vs. co-pilot: autopilot runs the plane but the pilot can take over anytime and must be watching. RMF 1.1 says high-stakes agentic systems need the co-pilot model, not just an emergency stop button.",
      executiveBrief: "Agentic AI deployments — internal coding agents, autonomous data workflows, AI-driven customer interactions — now have formal NIST governance requirements. Recommend a one-quarter audit of all agentic systems against the RMF 1.1 draft. Organizations that align now will be ahead of the formal effective date.",
    },
  ],
};
