import type { BriefingRecord } from "./db/schema";

export const MOCK_BRIEFING: BriefingRecord = {
  id: "mock-001",
  date: new Date().toISOString().split("T")[0],
  personaKey: "default",
  articlesFetched: 142,
  generatedAt: new Date().toISOString(),
  sections: {
    executiveSummary: [
      "Agentic AI is entering enterprise procurement as a standard line item — not a pilot.",
      "EU AI Act enforcement has begun; first fines signal regulators mean business.",
      "Claude 4 Opus context window changes make RAG architecture decisions less critical.",
    ],
    quickHits: "**OpenAI releases o3-mini pricing at 60% lower than o3** — competitive pressure on Anthropic and Google intensifies. **Mistral releases Codestral 2501** — open-source coding model closes gap with GPT-4o on HumanEval. **LangGraph v0.3 ships persistent memory** — stateful agents now 40% easier to build.",
    research: "**arXiv: 'Constitutional AI at Scale'** — Anthropic's new paper shows Constitutional AI principles can be applied to models 100× smaller than Claude 3. Key finding: alignment tax drops from 12% to 4% performance penalty at smaller scales. **DeepMind: 'Gemini's Tool Use Reliability'** — benchmark shows 23% improvement in multi-step tool calling accuracy vs. GPT-4o.",
    governance: "**EU AI Act Article 6 enforcement begins** — High-risk AI systems now require conformity assessment before deployment in EU. First enforcement actions target HR screening tools and credit scoring. **NIST AI RMF 1.1 draft published** — adds Agentic AI section covering autonomous decision loops, human override requirements, and audit trail specifications.",
    driveTime: "**Drive Time — Signal 1: EU AI Act Enforcement**\n\nGood morning. Let's talk about what happened yesterday in Brussels.\n\nThe EU's AI Office fined three companies a combined €2.1 million for deploying high-risk AI systems without conformity assessments. These are not giants — they're mid-market HR tech companies using automated screening tools.\n\nHere's what this means for you if you're building or advising on enterprise AI: the grace period is over. If your system touches hiring, credit, healthcare, or critical infrastructure, you need a conformity assessment now. Not in Q3. Now.\n\nThe practical checklist: First, classify your system under Annex III. Second, if it's high-risk, initiate a conformity assessment with an accredited notified body. Third, document your training data provenance — that's what the first three audits focused on.\n\nThe good news: NIST AI RMF alignment gets you 60–70% of the way to EU AI Act compliance. If you've done the RMF work, you're not starting from zero.\n\nBottom line: regulators are moving faster than most enterprises expected. The companies that get fined next will be the ones who thought they had more time.",
  },
  signals: [
    {
      number: 1,
      title: "EU AI Act Article 6 enforcement begins — first €2.1M in fines issued",
      classification: "Governance Alert",
      whatHappened: "The EU AI Office issued its first enforcement actions under the EU AI Act, fining three companies for deploying high-risk AI systems without completing required conformity assessments. The systems in question were automated CV screening and credit scoring tools.",
      whyItMatters: "This signals the end of the regulatory grace period. The EU is moving faster than most enterprises planned for, and the fines — while not enormous — establish precedent for what triggers enforcement.",
      sdlcImpact: "Any AI system touching HR, credit, healthcare, or critical infrastructure must now have a conformity assessment completed before deployment in EU markets. This adds 2–4 months to release timelines for in-scope systems.",
      governanceImpact: "High direct impact. NIST AI RMF alignment covers ~60–70% of EU AI Act requirements. Enterprises already on RMF are best positioned. Training data provenance documentation was the primary audit focus.",
      architectureImpact: "Audit trail requirements now have teeth. Logging decisions, model versions, training data lineage, and human override events are no longer optional for high-risk systems.",
      myTake: "The companies fined are mid-market, not giants. Regulators are making examples. The message: they will go after whoever is easiest to audit, not whoever is biggest. Get your house in order.",
      linkedinAngle: "Most enterprises are treating EU AI Act compliance like a 2025 problem. It's a 2024 problem that's now a today problem.",
      hook: "The EU just fined three companies €2.1M for deploying AI without a conformity assessment. The grace period is over.",
    },
    {
      number: 2,
      title: "GitHub Copilot Workspace hits 500K enterprise seats in 90 days",
      classification: "Strategic Signal",
      whatHappened: "GitHub reported that Copilot Workspace — its agentic coding environment that can take a GitHub Issue and propose, implement, and test a fix end-to-end — has reached 500,000 enterprise seats in its first 90 days of GA.",
      whyItMatters: "Agentic coding is now a standard enterprise procurement line item, not an experiment. This scale validates the market faster than any analyst prediction.",
      sdlcImpact: "Code review workflows change fundamentally when the agent produces the diff, not the human. Teams need new review criteria: evaluating intent alignment, not just code correctness.",
      governanceImpact: "IP ownership questions emerge at scale. Who owns code generated by an agent acting on a GitHub Issue? Most enterprise contracts don't have language for this.",
      architectureImpact: "Issue-to-PR automation changes how you structure backlogs. Vague Issues get worse results from agents than from humans. Issue quality becomes a first-class engineering discipline.",
      myTake: "500K seats in 90 days is a product-market fit signal at the same scale as Slack's early growth. The SDLC is being restructured around human-in-the-loop review of agent output, not human-in-the-loop writing of code.",
      linkedinAngle: "Your junior engineers are not being replaced by AI. They're being promoted to reviewing AI output. The bar for what counts as 'junior' work just shifted up.",
      hook: "500K enterprise seats in 90 days. Agentic coding is not a pilot anymore — it's a procurement line item.",
    },
    {
      number: 3,
      title: "NIST AI RMF 1.1 draft adds Agentic AI section with human override requirements",
      classification: "Governance Alert",
      whatHappened: "NIST published the draft of AI RMF version 1.1, adding a dedicated section on Agentic AI systems covering autonomous decision loops, human override mechanisms, audit trail specifications, and multi-agent coordination risks.",
      whyItMatters: "NIST RMF is the de facto governance standard for US federal contractors and increasingly for regulated industries. This draft signals that agentic systems now require explicit governance design, not just general AI risk management.",
      sdlcImpact: "Agentic SDLC tools (coding agents, autonomous deployment pipelines, AI-driven testing) now fall under RMF scope explicitly. Teams building internal agents need to design override mechanisms before deployment, not retrofit them.",
      governanceImpact: "The draft specifies that 'human-in-the-loop' is insufficient for high-stakes agentic decisions — it requires 'human-on-the-loop' with documented escalation criteria and response SLAs.",
      architectureImpact: "Audit trail requirements for multi-agent systems are new: every agent-to-agent handoff must be logged with decision rationale, not just inputs/outputs. This affects LangGraph, CrewAI, and similar frameworks.",
      myTake: "NIST is six months ahead of where most enterprise architecture teams think the governance conversation is. If you're building agents today without override mechanisms, you're building technical debt that will be expensive to retrofit.",
      linkedinAngle: "NIST just added agentic AI to its risk framework. 'Human-in-the-loop' is no longer good enough — you need 'human-on-the-loop' with documented escalation paths.",
      hook: "NIST says human-in-the-loop is not enough for agentic AI. Here's what human-on-the-loop actually means in practice.",
    },
  ],
};
